before_script:
    - . ./acs-ci-config/config-common/set-ci-env.sh
script:
    - echo "Running unit and controller tests for NON-hierarchical attributes"
    - mvn -Ppostgres clean verify -B
    - echo "Running unit and controller tests for hierarchical attributes"
    - mvn verify deploy -s acs-ci-config/mvn_settings.xml -Ppredix -Dartifactory.password=${ARTIFACTORY_PASSWORD} -B
#    - mvn verify deploy -s acs-ci-config/mvn_settings.xml -Pwith.jacoco -Dartifactory.password=${ARTIFACTORY_PASSWORD} -B
#    - tar zcvf acs-model-jacoco.tar.gz model/target/site/jacoco
#    - tar zcvf acs-commons-jacoco.tar.gz commons/target/site/jacoco
#    - tar zcvf acs-service-jacoco.tar.gz service/target/site/jacoco
